# -*- coding: utf-8 -*-
"""carevision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pn5khn90jNfor8cLjnm6AvMffq5jr2s6
"""

!pip install -U gradio
!pip install slack-bolt
!pip install gradio_client
!pip install httpx

import gradio as gr

def chatbot(message, history):
    return "You said: " + message

demo = gr.ChatInterface(chatbot)

demo.launch()

from google.colab import userdata

from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler

# Load tokens
SLACK_BOT_TOKEN = userdata.get("SLACK_BOT_TOKEN")
SLACK_APP_TOKEN = userdata.get("SLACK_APP_TOKEN")

# Create Slack App
app = App(token=SLACK_BOT_TOKEN)

# When someone mentions @CareVision
@app.event("app_mention")
def handle_mentions(body, say):

    user = body["event"]["user"]
    text = body["event"]["text"]

    # Remove the bot mention
    bot_id = body["authorizations"][0]["user_id"]
    text = text.replace(f"<@{bot_id}>", "").strip()

    if text == "":
        say(f"👋 Hello <@{user}>! I am *CareVision*. How can I help you today?")
        return

    say(
        f"""🩺 *CareVision*

Hello <@{user}>!

You asked:

>{text}

This is where your AI response will appear.
"""
    )

if __name__ == "__main__":
    SocketModeHandler(app, SLACK_APP_TOKEN).start()

import gradio as gr

def carevision(message, history):
    return f"🩺 CareVision AI\n\nYou asked:\n{message}"

demo = gr.ChatInterface(
    fn=carevision,
    title="CareVision AI",
    description="Your AI Healthcare Assistant"
)

demo.launch(share=True)

