# -*- coding: utf-8 -*-
"""MediScribe_AI_OpenAI_Agents.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aOt0kvsQuhuB5ds_n4AQVaA5eDLVivlA
"""

!pip install -q openai-agents
!pip install -q openai
!pip install -q reportlab
!pip install -q python-dotenv
!pip install -q pydantic

import os
from getpass import getpass

os.environ["OPENAI_API_KEY"] = getpass("Enter your OpenAI API Key: ")

import agents

print("OpenAI Agents SDK installed successfully!")

from agents import Agent

history_agent = Agent(
    name="Patient History Agent",
    instructions="""
You are an expert medical assistant.

Your responsibility is to retrieve and organize patient history.

Return:

- Patient demographics
- Medical history
- Previous diagnoses
- Current medications
- Allergies
- Previous consultations

Always return JSON.
"""
)

from agents import Agent

clinical_note_agent = Agent(
    name="Clinical Note Writer",

    instructions="""
You are an experienced clinical documentation specialist.

Generate professional SOAP Notes.

Format:

Subjective

Objective

Assessment

Plan

Return structured JSON.
"""
)

from agents import Agent

summary_agent = Agent(
    name="Medical Summary Agent",

    instructions="""
Summarize the consultation.

Include:

Diagnosis

Symptoms

Medicines

Investigations

Follow-up

Return JSON.
"""
)

from agents import Agent

treatment_agent = Agent(
    name="Treatment Planner",

    instructions="""
You are an evidence-based medical assistant.

Suggest

Medicines

Laboratory tests

Lifestyle advice

Follow-up recommendations

Do NOT invent patient information.

Return JSON.
"""
)

from agents import Agent

reviewer_agent = Agent(
    name="Documentation Reviewer",

    instructions="""
Review every medical report.

Check:

Missing information

Formatting

Medical consistency

Spelling

Grammar

If something is missing, explain it.

Return JSON.
"""
)

from agents import Agent

report_agent = Agent(
    name="Report Generator",

    instructions="""
Generate a final medical report.

Include:

Patient Information

Clinical Notes

Summary

Treatment

Follow-up

The report should be ready for PDF generation.

Return clean markdown.
"""
)