# -*- coding: utf-8 -*-
"""TelegramBot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PXXOHmzOXU09Vh8MSwTiL2zK2KpqSHJV
"""

!pip install -U aiogram

!pip install openai

import asyncio
from aiogram import Bot, Dispatcher, types
from aiogram.filters import Command
import openai
import os
import sys
import logging

from google.colab import userdata

os.environ['OPENAI_API_KEY'] = userdata.get('OPENAI_API_KEY')

os.environ['TELEGRAM_BOT_TOKEN'] = userdata.get('TELEGRAM_BOT_TOKEN')

dp = Dispatcher()

@dp.message(Command('start'))
async def command_start(message: types.Message):
  "This handler will recieve the Message with /start command"

  await message.reply("Hi!\nI'm SS26 BOT!\nPowered by SummerSchool26.")

@dp.message(Command('help'))
async def help(message: types.Message):
    'This will receive Message with /help command'

    help_text="""
    Refer to these commands:
    /start - to start the bot
    /help - to get help
    """

    await message.reply(help_text)

# # other messages
# @dp.message()
# async def other_messages(message: types.Message):
#   "Will handle all other messages"

#   await message.reply(message.text)

context = []

#using chatgpt

@dp.message()
async def chatgpt(message: types.Message):
  "Will handle all other messages"

  print(f"User: {message.text}")

  context.append({'role':'user', 'content':f"{message.text}"})

  response = openai.chat.completions.create(
    model="gpt-4O-mini",
    messages=context
  )

  value = response.choices[0].message.content
  print(f"Bot response: {value}")

  print(context)

  context.append({'role':'assistant', 'content':f"{value}"})

  print(context)

  await message.reply(value)

async def main() -> None:
  bot = Bot(os.environ['TELEGRAM_BOT_TOKEN'])
  await dp.start_polling(bot)

if __name__ == "__main__":
  logging.basicConfig(level=logging.INFO, stream=sys.stdout)
  await main()

